### PR TITLE
Add Maven pom.xml and common .gitignore

### PR DESCRIPTION
**Pull request by httpdigest**
This adds a Maven pom.xml file with all dependencies, including the platform's LWJGL 3 natives, and also a Java .gitignore file for all common IDEs and build systems.

### CODE REVIEW

**Comment by integeruser** [comment]
Thanks again!

**Comment by integeruser** [comment]
```
<properties>
	<lwjgl.version>3.1.1-SNAPSHOT</lwjgl.version>
	<joml.version>1.9.1-SNAPSHOT</joml.version>
</properties>
```
Shouldn't we target, say, versions `3.1.0` and `1.9.0` which are known to work properly with `jgltut`? Never used Maven before so maybe I'm missing something.

**Comment by httpdigest** [comment]
Yes, there is a risk of using the latest version. But that's not so much a problem with Maven but with versioning in general. The risk here is that once the build of that snapshot version gets updated and becomes incompatible with the jgltut sources, the jgltut build will fail or we will get a runtime error.
At least with the lwjgl3-demos repository, we try to keep it in sync with the changes done to the lwjgl3 repository. We _could_ do the same for jgltut. However, that requires maintenance effort.
So, if you are unlikely to keep an eye out for potential changes in lwjgl3 and keep the jgltut demos up to date, then using a fixed version will be the better choice.

**Comment by integeruser** [comment]
It makes sense. I can't dedicate much time to this project anymore, and I will update it just once in a while. So, for now, I'm going to modify the POM to target `3.1.0` and `1.9.0`. Feel free (you, or anyone) to update it over time.

**Pull request merged**
